//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.09 at 03:33:38 PM EET 
//


package com.vmware.o11n.sdk.rest.client.stubs;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for array complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="array">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element name="sdk-object" type="{http://www.vmware.com/vco}sdk-object"/>
 *           &lt;element name="string" type="{http://www.vmware.com/vco}string"/>
 *           &lt;element name="secure-string" type="{http://www.vmware.com/vco}secure-string"/>
 *           &lt;element name="properties" type="{http://www.vmware.com/vco}properties"/>
 *           &lt;element name="number" type="{http://www.vmware.com/vco}number"/>
 *           &lt;element name="array" type="{http://www.vmware.com/vco}array"/>
 *           &lt;element name="mime-attachment" type="{http://www.vmware.com/vco}mime-attachment"/>
 *           &lt;element name="date" type="{http://www.vmware.com/vco}date"/>
 *           &lt;element name="boolean" type="{http://www.vmware.com/vco}boolean"/>
 *           &lt;element name="composite" type="{http://www.vmware.com/vco}composite"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "array", propOrder = {
    "sdkObjectOrStringOrSecureString"
})
public class Array {

    @XmlElements({
        @XmlElement(name = "sdk-object", type = SdkObject.class, nillable = true),
        @XmlElement(name = "string", type = String.class, nillable = true),
        @XmlElement(name = "secure-string", type = SecureString.class, nillable = true),
        @XmlElement(name = "properties", type = Properties.class, nillable = true),
        @XmlElement(name = "number", type = Double.class, nillable = true),
        @XmlElement(name = "array", type = Array.class, nillable = true),
        @XmlElement(name = "mime-attachment", type = MimeAttachment.class, nillable = true),
        @XmlElement(name = "date", type = XMLGregorianCalendar.class, nillable = true),
        @XmlElement(name = "boolean", type = Boolean.class, nillable = true),
        @XmlElement(name = "composite", type = Composite.class, nillable = true)
    })
    protected List<Object> sdkObjectOrStringOrSecureString;

    /**
     * Gets the value of the sdkObjectOrStringOrSecureString property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sdkObjectOrStringOrSecureString property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSdkObjectOrStringOrSecureString().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SdkObject }
     * {@link String }
     * {@link SecureString }
     * {@link Properties }
     * {@link Double }
     * {@link Array }
     * {@link MimeAttachment }
     * {@link XMLGregorianCalendar }
     * {@link Boolean }
     * {@link Composite }
     * 
     * 
     */
    public List<Object> getSdkObjectOrStringOrSecureString() {
        if (sdkObjectOrStringOrSecureString == null) {
            sdkObjectOrStringOrSecureString = new ArrayList<Object>();
        }
        return this.sdkObjectOrStringOrSecureString;
    }

}
