//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.09 at 03:33:38 PM EET 
//


package com.vmware.o11n.sdk.rest.client.stubs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for composite-value complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="composite-value">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="sdk-object" type="{http://www.vmware.com/vco}sdk-object"/>
 *           &lt;element name="string" type="{http://www.vmware.com/vco}string"/>
 *           &lt;element name="secure-string" type="{http://www.vmware.com/vco}secure-string"/>
 *           &lt;element name="properties" type="{http://www.vmware.com/vco}properties"/>
 *           &lt;element name="number" type="{http://www.vmware.com/vco}number"/>
 *           &lt;element name="array" type="{http://www.vmware.com/vco}array"/>
 *           &lt;element name="mime-attachment" type="{http://www.vmware.com/vco}mime-attachment"/>
 *           &lt;element name="date" type="{http://www.vmware.com/vco}date"/>
 *           &lt;element name="boolean" type="{http://www.vmware.com/vco}boolean"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "composite-value", propOrder = {
    "sdkObject",
    "string",
    "secureString",
    "properties",
    "number",
    "array",
    "mimeAttachment",
    "date",
    "_boolean"
})
public class CompositeValue {

    @XmlElement(name = "sdk-object")
    protected SdkObject sdkObject;
    protected String string;
    @XmlElement(name = "secure-string")
    protected SecureString secureString;
    protected Properties properties;
    protected Double number;
    protected Array array;
    @XmlElement(name = "mime-attachment")
    protected MimeAttachment mimeAttachment;
    protected XMLGregorianCalendar date;
    @XmlElement(name = "boolean")
    protected Boolean _boolean;
    @XmlAttribute(name = "id")
    protected String id;

    /**
     * Gets the value of the sdkObject property.
     * 
     * @return
     *     possible object is
     *     {@link SdkObject }
     *     
     */
    public SdkObject getSdkObject() {
        return sdkObject;
    }

    /**
     * Sets the value of the sdkObject property.
     * 
     * @param value
     *     allowed object is
     *     {@link SdkObject }
     *     
     */
    public void setSdkObject(SdkObject value) {
        this.sdkObject = value;
    }

    /**
     * Gets the value of the string property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getString() {
        return string;
    }

    /**
     * Sets the value of the string property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setString(String value) {
        this.string = value;
    }

    /**
     * Gets the value of the secureString property.
     * 
     * @return
     *     possible object is
     *     {@link SecureString }
     *     
     */
    public SecureString getSecureString() {
        return secureString;
    }

    /**
     * Sets the value of the secureString property.
     * 
     * @param value
     *     allowed object is
     *     {@link SecureString }
     *     
     */
    public void setSecureString(SecureString value) {
        this.secureString = value;
    }

    /**
     * Gets the value of the properties property.
     * 
     * @return
     *     possible object is
     *     {@link Properties }
     *     
     */
    public Properties getProperties() {
        return properties;
    }

    /**
     * Sets the value of the properties property.
     * 
     * @param value
     *     allowed object is
     *     {@link Properties }
     *     
     */
    public void setProperties(Properties value) {
        this.properties = value;
    }

    /**
     * Gets the value of the number property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getNumber() {
        return number;
    }

    /**
     * Sets the value of the number property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setNumber(Double value) {
        this.number = value;
    }

    /**
     * Gets the value of the array property.
     * 
     * @return
     *     possible object is
     *     {@link Array }
     *     
     */
    public Array getArray() {
        return array;
    }

    /**
     * Sets the value of the array property.
     * 
     * @param value
     *     allowed object is
     *     {@link Array }
     *     
     */
    public void setArray(Array value) {
        this.array = value;
    }

    /**
     * Gets the value of the mimeAttachment property.
     * 
     * @return
     *     possible object is
     *     {@link MimeAttachment }
     *     
     */
    public MimeAttachment getMimeAttachment() {
        return mimeAttachment;
    }

    /**
     * Sets the value of the mimeAttachment property.
     * 
     * @param value
     *     allowed object is
     *     {@link MimeAttachment }
     *     
     */
    public void setMimeAttachment(MimeAttachment value) {
        this.mimeAttachment = value;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDate(XMLGregorianCalendar value) {
        this.date = value;
    }

    /**
     * Gets the value of the boolean property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isBoolean() {
        return _boolean;
    }

    /**
     * Sets the value of the boolean property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBoolean(Boolean value) {
        this._boolean = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
