//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.09 at 03:33:38 PM EET 
//


package com.vmware.o11n.sdk.rest.client.stubs;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for field complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="field">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.vmware.com/vco}PresentationElement">
 *       &lt;sequence>
 *         &lt;element name="constraints" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;choice maxOccurs="unbounded" minOccurs="0">
 *                     &lt;element name="mandatory" type="{http://www.vmware.com/vco}mandatory"/>
 *                     &lt;element name="restrict-duplicates" type="{http://www.vmware.com/vco}restrictDuplicatesConstraint"/>
 *                     &lt;element name="regexp" type="{http://www.vmware.com/vco}regExp"/>
 *                     &lt;element name="number-range" type="{http://www.vmware.com/vco}rangeConstraint"/>
 *                     &lt;element name="number-format" type="{http://www.vmware.com/vco}numberFormat"/>
 *                   &lt;/choice>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="decorators" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;choice maxOccurs="unbounded" minOccurs="0">
 *                     &lt;element name="chooser" type="{http://www.vmware.com/vco}chooserDecorator"/>
 *                     &lt;element name="refresh-on-change" type="{http://www.vmware.com/vco}refreshOnChangeDecorator"/>
 *                     &lt;element name="drop-down" type="{http://www.vmware.com/vco}dropDownDecorator"/>
 *                     &lt;element name="multiline" type="{http://www.vmware.com/vco}multilineDecorator"/>
 *                   &lt;/choice>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "field", propOrder = {
    "constraints",
    "decorators"
})
@XmlSeeAlso({
    PrimaryField.class
})
public class Field
    extends PresentationElement
{

    protected Field.Constraints constraints;
    protected Field.Decorators decorators;
    @XmlAttribute(name = "type")
    protected String type;

    /**
     * Gets the value of the constraints property.
     * 
     * @return
     *     possible object is
     *     {@link Field.Constraints }
     *     
     */
    public Field.Constraints getConstraints() {
        return constraints;
    }

    /**
     * Sets the value of the constraints property.
     * 
     * @param value
     *     allowed object is
     *     {@link Field.Constraints }
     *     
     */
    public void setConstraints(Field.Constraints value) {
        this.constraints = value;
    }

    /**
     * Gets the value of the decorators property.
     * 
     * @return
     *     possible object is
     *     {@link Field.Decorators }
     *     
     */
    public Field.Decorators getDecorators() {
        return decorators;
    }

    /**
     * Sets the value of the decorators property.
     * 
     * @param value
     *     allowed object is
     *     {@link Field.Decorators }
     *     
     */
    public void setDecorators(Field.Decorators value) {
        this.decorators = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;choice maxOccurs="unbounded" minOccurs="0">
     *           &lt;element name="mandatory" type="{http://www.vmware.com/vco}mandatory"/>
     *           &lt;element name="restrict-duplicates" type="{http://www.vmware.com/vco}restrictDuplicatesConstraint"/>
     *           &lt;element name="regexp" type="{http://www.vmware.com/vco}regExp"/>
     *           &lt;element name="number-range" type="{http://www.vmware.com/vco}rangeConstraint"/>
     *           &lt;element name="number-format" type="{http://www.vmware.com/vco}numberFormat"/>
     *         &lt;/choice>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "mandatoryOrRestrictDuplicatesOrRegexp"
    })
    public static class Constraints {

        @XmlElements({
            @XmlElement(name = "mandatory", type = Mandatory.class),
            @XmlElement(name = "restrict-duplicates", type = RestrictDuplicatesConstraint.class),
            @XmlElement(name = "regexp", type = RegExp.class),
            @XmlElement(name = "number-range", type = RangeConstraint.class),
            @XmlElement(name = "number-format", type = NumberFormat.class)
        })
        protected List<Object> mandatoryOrRestrictDuplicatesOrRegexp;

        /**
         * Gets the value of the mandatoryOrRestrictDuplicatesOrRegexp property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the mandatoryOrRestrictDuplicatesOrRegexp property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getMandatoryOrRestrictDuplicatesOrRegexp().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Mandatory }
         * {@link RestrictDuplicatesConstraint }
         * {@link RegExp }
         * {@link RangeConstraint }
         * {@link NumberFormat }
         * 
         * 
         */
        public List<Object> getMandatoryOrRestrictDuplicatesOrRegexp() {
            if (mandatoryOrRestrictDuplicatesOrRegexp == null) {
                mandatoryOrRestrictDuplicatesOrRegexp = new ArrayList<Object>();
            }
            return this.mandatoryOrRestrictDuplicatesOrRegexp;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;choice maxOccurs="unbounded" minOccurs="0">
     *           &lt;element name="chooser" type="{http://www.vmware.com/vco}chooserDecorator"/>
     *           &lt;element name="refresh-on-change" type="{http://www.vmware.com/vco}refreshOnChangeDecorator"/>
     *           &lt;element name="drop-down" type="{http://www.vmware.com/vco}dropDownDecorator"/>
     *           &lt;element name="multiline" type="{http://www.vmware.com/vco}multilineDecorator"/>
     *         &lt;/choice>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "chooserOrRefreshOnChangeOrDropDown"
    })
    public static class Decorators {

        @XmlElements({
            @XmlElement(name = "chooser", type = ChooserDecorator.class),
            @XmlElement(name = "refresh-on-change", type = RefreshOnChangeDecorator.class),
            @XmlElement(name = "drop-down", type = DropDownDecorator.class),
            @XmlElement(name = "multiline", type = MultilineDecorator.class)
        })
        protected List<BaseDecorator> chooserOrRefreshOnChangeOrDropDown;

        /**
         * Gets the value of the chooserOrRefreshOnChangeOrDropDown property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the chooserOrRefreshOnChangeOrDropDown property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getChooserOrRefreshOnChangeOrDropDown().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ChooserDecorator }
         * {@link RefreshOnChangeDecorator }
         * {@link DropDownDecorator }
         * {@link MultilineDecorator }
         * 
         * 
         */
        public List<BaseDecorator> getChooserOrRefreshOnChangeOrDropDown() {
            if (chooserOrRefreshOnChangeOrDropDown == null) {
                chooserOrRefreshOnChangeOrDropDown = new ArrayList<BaseDecorator>();
            }
            return this.chooserOrRefreshOnChangeOrDropDown;
        }

    }

}
