//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.09 at 03:33:38 PM EET 
//


package com.vmware.o11n.sdk.rest.client.stubs;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.vmware.o11n.sdk.rest.client.stubs package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Workflow_QNAME = new QName("http://www.vmware.com/vco", "workflow");
    private final static QName _ExecutionContext_QNAME = new QName("http://www.vmware.com/vco", "execution-context");
    private final static QName _UserInteraction_QNAME = new QName("http://www.vmware.com/vco", "user-interaction");
    private final static QName _Resource_QNAME = new QName("http://www.vmware.com/vco", "resource");
    private final static QName _ModuleMetadata_QNAME = new QName("http://www.vmware.com/vco", "module-metadata");
    private final static QName _Permission_QNAME = new QName("http://www.vmware.com/vco", "permission");
    private final static QName _Tasks_QNAME = new QName("http://www.vmware.com/vco", "tasks");
    private final static QName _InventoryItem_QNAME = new QName("http://www.vmware.com/vco", "inventory-item");
    private final static QName _Logs_QNAME = new QName("http://www.vmware.com/vco", "logs");
    private final static QName _Task_QNAME = new QName("http://www.vmware.com/vco", "task");
    private final static QName _Executions_QNAME = new QName("http://www.vmware.com/vco", "executions");
    private final static QName _PackageDetails_QNAME = new QName("http://www.vmware.com/vco", "package-details");
    private final static QName _Packages_QNAME = new QName("http://www.vmware.com/vco", "packages");
    private final static QName _Configuration_QNAME = new QName("http://www.vmware.com/vco", "configuration");
    private final static QName _User_QNAME = new QName("http://www.vmware.com/vco", "user");
    private final static QName _Actions_QNAME = new QName("http://www.vmware.com/vco", "actions");
    private final static QName _Categories_QNAME = new QName("http://www.vmware.com/vco", "categories");
    private final static QName _Configurations_QNAME = new QName("http://www.vmware.com/vco", "configurations");
    private final static QName _ServiceDescriptors_QNAME = new QName("http://www.vmware.com/vco", "service-descriptors");
    private final static QName _Presentation_QNAME = new QName("http://www.vmware.com/vco", "presentation");
    private final static QName _Category_QNAME = new QName("http://www.vmware.com/vco", "category");
    private final static QName _InventoryItems_QNAME = new QName("http://www.vmware.com/vco", "inventory-items");
    private final static QName _Execution_QNAME = new QName("http://www.vmware.com/vco", "execution");
    private final static QName _Version_QNAME = new QName("http://www.vmware.com/vco", "version");
    private final static QName _State_QNAME = new QName("http://www.vmware.com/vco", "state");
    private final static QName _CategoryContext_QNAME = new QName("http://www.vmware.com/vco", "category-context");
    private final static QName _Descriptor_QNAME = new QName("http://www.vmware.com/vco", "descriptor");
    private final static QName _Resources_QNAME = new QName("http://www.vmware.com/vco", "resources");
    private final static QName _WorkflowExecution_QNAME = new QName("http://www.vmware.com/vco", "workflow-execution");
    private final static QName _Permissions_QNAME = new QName("http://www.vmware.com/vco", "permissions");
    private final static QName _Action_QNAME = new QName("http://www.vmware.com/vco", "action");
    private final static QName _SupportedVersions_QNAME = new QName("http://www.vmware.com/vco", "supported-versions");
    private final static QName _TaskData_QNAME = new QName("http://www.vmware.com/vco", "task-data");
    private final static QName _AboutInfo_QNAME = new QName("http://www.vmware.com/vco", "about-info");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.vmware.o11n.sdk.rest.client.stubs
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Group }
     * 
     */
    public Group createGroup() {
        return new Group();
    }

    /**
     * Create an instance of {@link Field }
     * 
     */
    public Field createField() {
        return new Field();
    }

    /**
     * Create an instance of {@link PrimaryField }
     * 
     */
    public PrimaryField createPrimaryField() {
        return new PrimaryField();
    }

    /**
     * Create an instance of {@link TypeMetadata }
     * 
     */
    public TypeMetadata createTypeMetadata() {
        return new TypeMetadata();
    }

    /**
     * Create an instance of {@link Link }
     * 
     */
    public Link createLink() {
        return new Link();
    }

    /**
     * Create an instance of {@link Configuration }
     * 
     */
    public Configuration createConfiguration() {
        return new Configuration();
    }

    /**
     * Create an instance of {@link Presentation }
     * 
     */
    public Presentation createPresentation() {
        return new Presentation();
    }

    /**
     * Create an instance of {@link UserInteraction }
     * 
     */
    public UserInteraction createUserInteraction() {
        return new UserInteraction();
    }

    /**
     * Create an instance of {@link ExecutionContext }
     * 
     */
    public ExecutionContext createExecutionContext() {
        return new ExecutionContext();
    }

    /**
     * Create an instance of {@link Workflow }
     * 
     */
    public Workflow createWorkflow() {
        return new Workflow();
    }

    /**
     * Create an instance of {@link PluginMetadata }
     * 
     */
    public PluginMetadata createPluginMetadata() {
        return new PluginMetadata();
    }

    /**
     * Create an instance of {@link Task }
     * 
     */
    public Task createTask() {
        return new Task();
    }

    /**
     * Create an instance of {@link InventoryItem }
     * 
     */
    public InventoryItem createInventoryItem() {
        return new InventoryItem();
    }

    /**
     * Create an instance of {@link PackageContentDetails }
     * 
     */
    public PackageContentDetails createPackageContentDetails() {
        return new PackageContentDetails();
    }

    /**
     * Create an instance of {@link WorkflowExecution }
     * 
     */
    public WorkflowExecution createWorkflowExecution() {
        return new WorkflowExecution();
    }

    /**
     * Create an instance of {@link Action }
     * 
     */
    public Action createAction() {
        return new Action();
    }

    /**
     * Create an instance of {@link PresentationExecution }
     * 
     */
    public PresentationExecution createPresentationExecution() {
        return new PresentationExecution();
    }

    /**
     * Create an instance of {@link ResourcesList }
     * 
     */
    public ResourcesList createResourcesList() {
        return new ResourcesList();
    }

    /**
     * Create an instance of {@link CategoryContext }
     * 
     */
    public CategoryContext createCategoryContext() {
        return new CategoryContext();
    }

    /**
     * Create an instance of {@link Descriptor }
     * 
     */
    public Descriptor createDescriptor() {
        return new Descriptor();
    }

    /**
     * Create an instance of {@link InventoryItemsList }
     * 
     */
    public InventoryItemsList createInventoryItemsList() {
        return new InventoryItemsList();
    }

    /**
     * Create an instance of {@link Version }
     * 
     */
    public Version createVersion() {
        return new Version();
    }

    /**
     * Create an instance of {@link TaskData }
     * 
     */
    public TaskData createTaskData() {
        return new TaskData();
    }

    /**
     * Create an instance of {@link AboutInfo }
     * 
     */
    public AboutInfo createAboutInfo() {
        return new AboutInfo();
    }

    /**
     * Create an instance of {@link PermissionsList }
     * 
     */
    public PermissionsList createPermissionsList() {
        return new PermissionsList();
    }

    /**
     * Create an instance of {@link SupportedApiVersionsList }
     * 
     */
    public SupportedApiVersionsList createSupportedApiVersionsList() {
        return new SupportedApiVersionsList();
    }

    /**
     * Create an instance of {@link PresentationExecutionsList }
     * 
     */
    public PresentationExecutionsList createPresentationExecutionsList() {
        return new PresentationExecutionsList();
    }

    /**
     * Create an instance of {@link PackageList }
     * 
     */
    public PackageList createPackageList() {
        return new PackageList();
    }

    /**
     * Create an instance of {@link LogsList }
     * 
     */
    public LogsList createLogsList() {
        return new LogsList();
    }

    /**
     * Create an instance of {@link Resource }
     * 
     */
    public Resource createResource() {
        return new Resource();
    }

    /**
     * Create an instance of {@link PermissionEntry }
     * 
     */
    public PermissionEntry createPermissionEntry() {
        return new PermissionEntry();
    }

    /**
     * Create an instance of {@link TaskList }
     * 
     */
    public TaskList createTaskList() {
        return new TaskList();
    }

    /**
     * Create an instance of {@link Category }
     * 
     */
    public Category createCategory() {
        return new Category();
    }

    /**
     * Create an instance of {@link ConfigurationsList }
     * 
     */
    public ConfigurationsList createConfigurationsList() {
        return new ConfigurationsList();
    }

    /**
     * Create an instance of {@link CategoriesList }
     * 
     */
    public CategoriesList createCategoriesList() {
        return new CategoriesList();
    }

    /**
     * Create an instance of {@link ServiceDescriptorList }
     * 
     */
    public ServiceDescriptorList createServiceDescriptorList() {
        return new ServiceDescriptorList();
    }

    /**
     * Create an instance of {@link User }
     * 
     */
    public User createUser() {
        return new User();
    }

    /**
     * Create an instance of {@link ActionsList }
     * 
     */
    public ActionsList createActionsList() {
        return new ActionsList();
    }

    /**
     * Create an instance of {@link AttributeMetadata }
     * 
     */
    public AttributeMetadata createAttributeMetadata() {
        return new AttributeMetadata();
    }

    /**
     * Create an instance of {@link VisibleDecorator }
     * 
     */
    public VisibleDecorator createVisibleDecorator() {
        return new VisibleDecorator();
    }

    /**
     * Create an instance of {@link ChooserDecorator }
     * 
     */
    public ChooserDecorator createChooserDecorator() {
        return new ChooserDecorator();
    }

    /**
     * Create an instance of {@link DataBindingDecorator }
     * 
     */
    public DataBindingDecorator createDataBindingDecorator() {
        return new DataBindingDecorator();
    }

    /**
     * Create an instance of {@link DefaultValueDecorator }
     * 
     */
    public DefaultValueDecorator createDefaultValueDecorator() {
        return new DefaultValueDecorator();
    }

    /**
     * Create an instance of {@link PropertiesWriter }
     * 
     */
    public PropertiesWriter createPropertiesWriter() {
        return new PropertiesWriter();
    }

    /**
     * Create an instance of {@link Mandatory }
     * 
     */
    public Mandatory createMandatory() {
        return new Mandatory();
    }

    /**
     * Create an instance of {@link Relation }
     * 
     */
    public Relation createRelation() {
        return new Relation();
    }

    /**
     * Create an instance of {@link RangeConstraint }
     * 
     */
    public RangeConstraint createRangeConstraint() {
        return new RangeConstraint();
    }

    /**
     * Create an instance of {@link Properties }
     * 
     */
    public Properties createProperties() {
        return new Properties();
    }

    /**
     * Create an instance of {@link Composite }
     * 
     */
    public Composite createComposite() {
        return new Composite();
    }

    /**
     * Create an instance of {@link NumberFormat }
     * 
     */
    public NumberFormat createNumberFormat() {
        return new NumberFormat();
    }

    /**
     * Create an instance of {@link DropDownDecorator }
     * 
     */
    public DropDownDecorator createDropDownDecorator() {
        return new DropDownDecorator();
    }

    /**
     * Create an instance of {@link Array }
     * 
     */
    public Array createArray() {
        return new Array();
    }

    /**
     * Create an instance of {@link RefreshOnChangeDecorator }
     * 
     */
    public RefreshOnChangeDecorator createRefreshOnChangeDecorator() {
        return new RefreshOnChangeDecorator();
    }

    /**
     * Create an instance of {@link LogEntry }
     * 
     */
    public LogEntry createLogEntry() {
        return new LogEntry();
    }

    /**
     * Create an instance of {@link RegExp }
     * 
     */
    public RegExp createRegExp() {
        return new RegExp();
    }

    /**
     * Create an instance of {@link RelationMetadata }
     * 
     */
    public RelationMetadata createRelationMetadata() {
        return new RelationMetadata();
    }

    /**
     * Create an instance of {@link Attribute }
     * 
     */
    public Attribute createAttribute() {
        return new Attribute();
    }

    /**
     * Create an instance of {@link RestrictDuplicatesConstraint }
     * 
     */
    public RestrictDuplicatesConstraint createRestrictDuplicatesConstraint() {
        return new RestrictDuplicatesConstraint();
    }

    /**
     * Create an instance of {@link Parameter }
     * 
     */
    public Parameter createParameter() {
        return new Parameter();
    }

    /**
     * Create an instance of {@link MimeAttachment }
     * 
     */
    public MimeAttachment createMimeAttachment() {
        return new MimeAttachment();
    }

    /**
     * Create an instance of {@link ElementMessage }
     * 
     */
    public ElementMessage createElementMessage() {
        return new ElementMessage();
    }

    /**
     * Create an instance of {@link RootElementDecorator }
     * 
     */
    public RootElementDecorator createRootElementDecorator() {
        return new RootElementDecorator();
    }

    /**
     * Create an instance of {@link MultilineDecorator }
     * 
     */
    public MultilineDecorator createMultilineDecorator() {
        return new MultilineDecorator();
    }

    /**
     * Create an instance of {@link OgnlConstraint }
     * 
     */
    public OgnlConstraint createOgnlConstraint() {
        return new OgnlConstraint();
    }

    /**
     * Create an instance of {@link Step }
     * 
     */
    public Step createStep() {
        return new Step();
    }

    /**
     * Create an instance of {@link KeyValuePair }
     * 
     */
    public KeyValuePair createKeyValuePair() {
        return new KeyValuePair();
    }

    /**
     * Create an instance of {@link SdkObject }
     * 
     */
    public SdkObject createSdkObject() {
        return new SdkObject();
    }

    /**
     * Create an instance of {@link CompositeValue }
     * 
     */
    public CompositeValue createCompositeValue() {
        return new CompositeValue();
    }

    /**
     * Create an instance of {@link com.vmware.o11n.sdk.rest.client.stubs.Relations }
     * 
     */
    public com.vmware.o11n.sdk.rest.client.stubs.Relations createRelations() {
        return new com.vmware.o11n.sdk.rest.client.stubs.Relations();
    }

    /**
     * Create an instance of {@link SecureString }
     * 
     */
    public SecureString createSecureString() {
        return new SecureString();
    }

    /**
     * Create an instance of {@link com.vmware.o11n.sdk.rest.client.stubs.PresentationElement.Messages }
     * 
     */
    public com.vmware.o11n.sdk.rest.client.stubs.PresentationElement.Messages createPresentationElementMessages() {
        return new com.vmware.o11n.sdk.rest.client.stubs.PresentationElement.Messages();
    }

    /**
     * Create an instance of {@link Group.Fields }
     * 
     */
    public Group.Fields createGroupFields() {
        return new Group.Fields();
    }

    /**
     * Create an instance of {@link com.vmware.o11n.sdk.rest.client.stubs.AbstractPresentationContent.Steps }
     * 
     */
    public com.vmware.o11n.sdk.rest.client.stubs.AbstractPresentationContent.Steps createAbstractPresentationContentSteps() {
        return new com.vmware.o11n.sdk.rest.client.stubs.AbstractPresentationContent.Steps();
    }

    /**
     * Create an instance of {@link Field.Constraints }
     * 
     */
    public Field.Constraints createFieldConstraints() {
        return new Field.Constraints();
    }

    /**
     * Create an instance of {@link Field.Decorators }
     * 
     */
    public Field.Decorators createFieldDecorators() {
        return new Field.Decorators();
    }

    /**
     * Create an instance of {@link PrimaryField.Fields }
     * 
     */
    public PrimaryField.Fields createPrimaryFieldFields() {
        return new PrimaryField.Fields();
    }

    /**
     * Create an instance of {@link TypeMetadata.Attributes }
     * 
     */
    public TypeMetadata.Attributes createTypeMetadataAttributes() {
        return new TypeMetadata.Attributes();
    }

    /**
     * Create an instance of {@link TypeMetadata.Relations }
     * 
     */
    public TypeMetadata.Relations createTypeMetadataRelations() {
        return new TypeMetadata.Relations();
    }

    /**
     * Create an instance of {@link Link.Attributes }
     * 
     */
    public Link.Attributes createLinkAttributes() {
        return new Link.Attributes();
    }

    /**
     * Create an instance of {@link Configuration.Attributes }
     * 
     */
    public Configuration.Attributes createConfigurationAttributes() {
        return new Configuration.Attributes();
    }

    /**
     * Create an instance of {@link Presentation.InputParameters }
     * 
     */
    public Presentation.InputParameters createPresentationInputParameters() {
        return new Presentation.InputParameters();
    }

    /**
     * Create an instance of {@link Presentation.OutputParameters }
     * 
     */
    public Presentation.OutputParameters createPresentationOutputParameters() {
        return new Presentation.OutputParameters();
    }

    /**
     * Create an instance of {@link UserInteraction.InputParameters }
     * 
     */
    public UserInteraction.InputParameters createUserInteractionInputParameters() {
        return new UserInteraction.InputParameters();
    }

    /**
     * Create an instance of {@link ExecutionContext.Parameters }
     * 
     */
    public ExecutionContext.Parameters createExecutionContextParameters() {
        return new ExecutionContext.Parameters();
    }

    /**
     * Create an instance of {@link Workflow.InputParameters }
     * 
     */
    public Workflow.InputParameters createWorkflowInputParameters() {
        return new Workflow.InputParameters();
    }

    /**
     * Create an instance of {@link Workflow.OutputParameters }
     * 
     */
    public Workflow.OutputParameters createWorkflowOutputParameters() {
        return new Workflow.OutputParameters();
    }

    /**
     * Create an instance of {@link PluginMetadata.Types }
     * 
     */
    public PluginMetadata.Types createPluginMetadataTypes() {
        return new PluginMetadata.Types();
    }

    /**
     * Create an instance of {@link Task.InputParameters }
     * 
     */
    public Task.InputParameters createTaskInputParameters() {
        return new Task.InputParameters();
    }

    /**
     * Create an instance of {@link InventoryItem.Attributes }
     * 
     */
    public InventoryItem.Attributes createInventoryItemAttributes() {
        return new InventoryItem.Attributes();
    }

    /**
     * Create an instance of {@link PackageContentDetails.Workflows }
     * 
     */
    public PackageContentDetails.Workflows createPackageContentDetailsWorkflows() {
        return new PackageContentDetails.Workflows();
    }

    /**
     * Create an instance of {@link PackageContentDetails.Actions }
     * 
     */
    public PackageContentDetails.Actions createPackageContentDetailsActions() {
        return new PackageContentDetails.Actions();
    }

    /**
     * Create an instance of {@link WorkflowExecution.InputParameters }
     * 
     */
    public WorkflowExecution.InputParameters createWorkflowExecutionInputParameters() {
        return new WorkflowExecution.InputParameters();
    }

    /**
     * Create an instance of {@link WorkflowExecution.OutputParameters }
     * 
     */
    public WorkflowExecution.OutputParameters createWorkflowExecutionOutputParameters() {
        return new WorkflowExecution.OutputParameters();
    }

    /**
     * Create an instance of {@link Action.InputParameters }
     * 
     */
    public Action.InputParameters createActionInputParameters() {
        return new Action.InputParameters();
    }

    /**
     * Create an instance of {@link PresentationExecution.OutputParameters }
     * 
     */
    public PresentationExecution.OutputParameters createPresentationExecutionOutputParameters() {
        return new PresentationExecution.OutputParameters();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Workflow }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.vmware.com/vco", name = "workflow")
    public JAXBElement<Workflow> createWorkflow(Workflow value) {
        return new JAXBElement<Workflow>(_Workflow_QNAME, Workflow.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExecutionContext }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.vmware.com/vco", name = "execution-context")
    public JAXBElement<ExecutionContext> createExecutionContext(ExecutionContext value) {
        return new JAXBElement<ExecutionContext>(_ExecutionContext_QNAME, ExecutionContext.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UserInteraction }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.vmware.com/vco", name = "user-interaction")
    public JAXBElement<UserInteraction> createUserInteraction(UserInteraction value) {
        return new JAXBElement<UserInteraction>(_UserInteraction_QNAME, UserInteraction.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Resource }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.vmware.com/vco", name = "resource")
    public JAXBElement<Resource> createResource(Resource value) {
        return new JAXBElement<Resource>(_Resource_QNAME, Resource.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PluginMetadata }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.vmware.com/vco", name = "module-metadata")
    public JAXBElement<PluginMetadata> createModuleMetadata(PluginMetadata value) {
        return new JAXBElement<PluginMetadata>(_ModuleMetadata_QNAME, PluginMetadata.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PermissionEntry }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.vmware.com/vco", name = "permission")
    public JAXBElement<PermissionEntry> createPermission(PermissionEntry value) {
        return new JAXBElement<PermissionEntry>(_Permission_QNAME, PermissionEntry.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TaskList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.vmware.com/vco", name = "tasks")
    public JAXBElement<TaskList> createTasks(TaskList value) {
        return new JAXBElement<TaskList>(_Tasks_QNAME, TaskList.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InventoryItem }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.vmware.com/vco", name = "inventory-item")
    public JAXBElement<InventoryItem> createInventoryItem(InventoryItem value) {
        return new JAXBElement<InventoryItem>(_InventoryItem_QNAME, InventoryItem.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LogsList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.vmware.com/vco", name = "logs")
    public JAXBElement<LogsList> createLogs(LogsList value) {
        return new JAXBElement<LogsList>(_Logs_QNAME, LogsList.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Task }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.vmware.com/vco", name = "task")
    public JAXBElement<Task> createTask(Task value) {
        return new JAXBElement<Task>(_Task_QNAME, Task.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PresentationExecutionsList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.vmware.com/vco", name = "executions")
    public JAXBElement<PresentationExecutionsList> createExecutions(PresentationExecutionsList value) {
        return new JAXBElement<PresentationExecutionsList>(_Executions_QNAME, PresentationExecutionsList.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PackageContentDetails }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.vmware.com/vco", name = "package-details")
    public JAXBElement<PackageContentDetails> createPackageDetails(PackageContentDetails value) {
        return new JAXBElement<PackageContentDetails>(_PackageDetails_QNAME, PackageContentDetails.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PackageList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.vmware.com/vco", name = "packages")
    public JAXBElement<PackageList> createPackages(PackageList value) {
        return new JAXBElement<PackageList>(_Packages_QNAME, PackageList.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Configuration }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.vmware.com/vco", name = "configuration")
    public JAXBElement<Configuration> createConfiguration(Configuration value) {
        return new JAXBElement<Configuration>(_Configuration_QNAME, Configuration.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link User }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.vmware.com/vco", name = "user")
    public JAXBElement<User> createUser(User value) {
        return new JAXBElement<User>(_User_QNAME, User.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ActionsList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.vmware.com/vco", name = "actions")
    public JAXBElement<ActionsList> createActions(ActionsList value) {
        return new JAXBElement<ActionsList>(_Actions_QNAME, ActionsList.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CategoriesList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.vmware.com/vco", name = "categories")
    public JAXBElement<CategoriesList> createCategories(CategoriesList value) {
        return new JAXBElement<CategoriesList>(_Categories_QNAME, CategoriesList.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConfigurationsList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.vmware.com/vco", name = "configurations")
    public JAXBElement<ConfigurationsList> createConfigurations(ConfigurationsList value) {
        return new JAXBElement<ConfigurationsList>(_Configurations_QNAME, ConfigurationsList.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServiceDescriptorList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.vmware.com/vco", name = "service-descriptors")
    public JAXBElement<ServiceDescriptorList> createServiceDescriptors(ServiceDescriptorList value) {
        return new JAXBElement<ServiceDescriptorList>(_ServiceDescriptors_QNAME, ServiceDescriptorList.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Presentation }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.vmware.com/vco", name = "presentation")
    public JAXBElement<Presentation> createPresentation(Presentation value) {
        return new JAXBElement<Presentation>(_Presentation_QNAME, Presentation.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Category }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.vmware.com/vco", name = "category")
    public JAXBElement<Category> createCategory(Category value) {
        return new JAXBElement<Category>(_Category_QNAME, Category.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InventoryItemsList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.vmware.com/vco", name = "inventory-items")
    public JAXBElement<InventoryItemsList> createInventoryItems(InventoryItemsList value) {
        return new JAXBElement<InventoryItemsList>(_InventoryItems_QNAME, InventoryItemsList.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PresentationExecution }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.vmware.com/vco", name = "execution")
    public JAXBElement<PresentationExecution> createExecution(PresentationExecution value) {
        return new JAXBElement<PresentationExecution>(_Execution_QNAME, PresentationExecution.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Version }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.vmware.com/vco", name = "version")
    public JAXBElement<Version> createVersion(Version value) {
        return new JAXBElement<Version>(_Version_QNAME, Version.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WorkflowExecutionState }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.vmware.com/vco", name = "state")
    public JAXBElement<WorkflowExecutionState> createState(WorkflowExecutionState value) {
        return new JAXBElement<WorkflowExecutionState>(_State_QNAME, WorkflowExecutionState.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CategoryContext }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.vmware.com/vco", name = "category-context")
    public JAXBElement<CategoryContext> createCategoryContext(CategoryContext value) {
        return new JAXBElement<CategoryContext>(_CategoryContext_QNAME, CategoryContext.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Descriptor }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.vmware.com/vco", name = "descriptor")
    public JAXBElement<Descriptor> createDescriptor(Descriptor value) {
        return new JAXBElement<Descriptor>(_Descriptor_QNAME, Descriptor.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResourcesList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.vmware.com/vco", name = "resources")
    public JAXBElement<ResourcesList> createResources(ResourcesList value) {
        return new JAXBElement<ResourcesList>(_Resources_QNAME, ResourcesList.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WorkflowExecution }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.vmware.com/vco", name = "workflow-execution")
    public JAXBElement<WorkflowExecution> createWorkflowExecution(WorkflowExecution value) {
        return new JAXBElement<WorkflowExecution>(_WorkflowExecution_QNAME, WorkflowExecution.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PermissionsList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.vmware.com/vco", name = "permissions")
    public JAXBElement<PermissionsList> createPermissions(PermissionsList value) {
        return new JAXBElement<PermissionsList>(_Permissions_QNAME, PermissionsList.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Action }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.vmware.com/vco", name = "action")
    public JAXBElement<Action> createAction(Action value) {
        return new JAXBElement<Action>(_Action_QNAME, Action.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SupportedApiVersionsList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.vmware.com/vco", name = "supported-versions")
    public JAXBElement<SupportedApiVersionsList> createSupportedVersions(SupportedApiVersionsList value) {
        return new JAXBElement<SupportedApiVersionsList>(_SupportedVersions_QNAME, SupportedApiVersionsList.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TaskData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.vmware.com/vco", name = "task-data")
    public JAXBElement<TaskData> createTaskData(TaskData value) {
        return new JAXBElement<TaskData>(_TaskData_QNAME, TaskData.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AboutInfo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.vmware.com/vco", name = "about-info")
    public JAXBElement<AboutInfo> createAboutInfo(AboutInfo value) {
        return new JAXBElement<AboutInfo>(_AboutInfo_QNAME, AboutInfo.class, null, value);
    }

}
