//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.09 at 03:33:38 PM EET 
//


package com.vmware.o11n.sdk.rest.client.stubs;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for recurrenceCycle.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="recurrenceCycle">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="one-time"/>
 *     &lt;enumeration value="every-minutes"/>
 *     &lt;enumeration value="every-hours"/>
 *     &lt;enumeration value="every-days"/>
 *     &lt;enumeration value="every-weeks"/>
 *     &lt;enumeration value="every-months"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "recurrenceCycle")
@XmlEnum
public enum RecurrenceCycle {

    @XmlEnumValue("one-time")
    ONE_TIME("one-time"),
    @XmlEnumValue("every-minutes")
    EVERY_MINUTES("every-minutes"),
    @XmlEnumValue("every-hours")
    EVERY_HOURS("every-hours"),
    @XmlEnumValue("every-days")
    EVERY_DAYS("every-days"),
    @XmlEnumValue("every-weeks")
    EVERY_WEEKS("every-weeks"),
    @XmlEnumValue("every-months")
    EVERY_MONTHS("every-months");
    private final String value;

    RecurrenceCycle(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static RecurrenceCycle fromValue(String v) {
        for (RecurrenceCycle c: RecurrenceCycle.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
