//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.09 at 03:33:38 PM EET 
//


package com.vmware.o11n.sdk.rest.client.stubs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for rootElementDecorator complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="rootElementDecorator">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.vmware.com/vco}baseDecorator">
 *       &lt;sequence>
 *         &lt;element name="sdk-object" type="{http://www.vmware.com/vco}sdk-object" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "rootElementDecorator", propOrder = {
    "sdkObject"
})
public class RootElementDecorator
    extends BaseDecorator
{

    @XmlElement(name = "sdk-object")
    protected SdkObject sdkObject;

    /**
     * Gets the value of the sdkObject property.
     * 
     * @return
     *     possible object is
     *     {@link SdkObject }
     *     
     */
    public SdkObject getSdkObject() {
        return sdkObject;
    }

    /**
     * Sets the value of the sdkObject property.
     * 
     * @param value
     *     allowed object is
     *     {@link SdkObject }
     *     
     */
    public void setSdkObject(SdkObject value) {
        this.sdkObject = value;
    }

}
