//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.09 at 03:33:38 PM EET 
//


package com.vmware.o11n.sdk.rest.client.stubs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for user complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="user">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="admin-rights" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="solution-user" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "user")
@XmlRootElement(name = "user")
public class User {

    @XmlAttribute(name = "admin-rights", required = true)
    protected boolean adminRights;
    @XmlAttribute(name = "solution-user", required = true)
    protected String solutionUser;

    /**
     * Gets the value of the adminRights property.
     * 
     */
    public boolean isAdminRights() {
        return adminRights;
    }

    /**
     * Sets the value of the adminRights property.
     * 
     */
    public void setAdminRights(boolean value) {
        this.adminRights = value;
    }

    /**
     * Gets the value of the solutionUser property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSolutionUser() {
        return solutionUser;
    }

    /**
     * Sets the value of the solutionUser property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSolutionUser(String value) {
        this.solutionUser = value;
    }

}
